#!/usr/bin/env bash
# Creates a backup file and a compress backup file from sql db
mysqldump -u root -p"$1" --all-databases > backup.sql
mysqldump -u root -p"$1" --all-databases | gzip > $(date +%d-%m-%Y).tar.gz
