#!/usr/bin/env bash
# Debug a container to make 'curl 0:80' work
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sed -i 's/pid /run/nginx.pid/pid /run/fake.pid/' /etc/nginx/nginx.conf
