#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS
IFS=':'
while read -r USERNAME PASSWORD USER_ID GROUP_ID GECOS HOME_DIRECTORY COMMAND
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $GECOS"
done < "/etc/passwd"
